using LnnMoeBook.Core;
using LnnMoeBook.Examples.Backprop;
using LnnMoeBook.Examples.CfC;
using LnnMoeBook.Examples.Concepts;
using LnnMoeBook.Examples.Ctrnn;
using LnnMoeBook.Examples.Data;
using LnnMoeBook.Examples.Distributed;
using LnnMoeBook.Examples.Dynamics;
using LnnMoeBook.Examples.Evaluation;
using LnnMoeBook.Examples.Hybrid;
using LnnMoeBook.Examples.LinearAlgebra;
using LnnMoeBook.Examples.LTC;
using LnnMoeBook.Examples.Memory;
using LnnMoeBook.Examples.MoE;
using LnnMoeBook.Examples.Mlp;
using LnnMoeBook.Examples.NeuralOde;
using LnnMoeBook.Examples.Optimization;
using LnnMoeBook.Examples.Perceptron;
using LnnMoeBook.Examples.QayaCaseStudy;
using LnnMoeBook.Examples.Rnn;
using LnnMoeBook.Examples.Training;

Console.WriteLine(BookProjectInfo.GetStatus());
Console.WriteLine(TorchSharpDiagnostics.RunSmokeTest().ToDiagnosticLine());
Console.WriteLine(TensorBasics.FormatReport(TensorBasics.Run()));
Console.WriteLine(Distances.FormatReport(Distances.Run()));
Console.WriteLine(GradientDescent1D.FormatReport(GradientDescent1D.RunDefault()));
Console.WriteLine(AdamFromScratch.FormatReport(AdamFromScratch.RunDefault()));
Console.WriteLine(EulerSolver.FormatReport(EulerSolver.RunDefault()));
Console.WriteLine(Rk4Solver.FormatReport(Rk4Solver.RunDefault()));
Console.WriteLine(PerceptronClassifier.FormatReport(PerceptronClassifier.RunDefault()));
Console.WriteLine(MlpClassifier.FormatReport(MlpClassifier.RunDefault()));
Console.WriteLine(RegularizationDemo.FormatReport(RegularizationDemo.RunDefault()));
Console.WriteLine(ManualBackprop.FormatReport(ManualBackprop.RunDefault()));
Console.WriteLine(GradientDiagnostics.FormatReport(GradientDiagnostics.RunDefault()));
Console.WriteLine(SimpleRnnForecast.FormatReport(SimpleRnnForecast.RunDefault()));
Console.WriteLine(LstmSequenceClassifier.FormatReport(LstmSequenceClassifier.RunDefault()));
Console.WriteLine(GruSequenceClassifier.FormatReport(GruSequenceClassifier.RunDefault()));
Console.WriteLine(IrregularTimeSeriesGenerator.FormatReport(IrregularTimeSeriesGenerator.RunDefault()));
Console.WriteLine(ToyNeuralOde.FormatReport(ToyNeuralOde.RunDefault()));
Console.WriteLine(SimpleCtrnnCell.FormatReport(SimpleCtrnnCell.RunDefault()));
Console.WriteLine(SimpleLtcCell.FormatReport(SimpleLtcCell.RunDefault()));
Console.WriteLine(LtcSequenceTrainer.FormatReport(LtcSequenceTrainer.RunDefault()));
Console.WriteLine(SimpleCfcCell.FormatReport(SimpleCfcCell.RunDefault()));
Console.WriteLine(RobustnessSuite.FormatReport(RobustnessSuite.RunDefault()));
Console.WriteLine(DenseExperts.FormatReport(DenseExperts.RunDefault()));
Console.WriteLine(TopKRouter.FormatReport(TopKRouter.RunDefault()));
Console.WriteLine(LoadBalancingLoss.FormatReport(LoadBalancingLoss.RunDefault()));
Console.WriteLine(SparseMoeLayer.FormatReport(SparseMoeLayer.RunDefault()));
Console.WriteLine(ShardingSimulator.FormatReport(ShardingSimulator.RunDefault()));
Console.WriteLine(SwitchRouter.FormatReport(SwitchRouter.RunDefault()));
Console.WriteLine(MixtralRouterToy.FormatReport(MixtralRouterToy.RunDefault()));
Console.WriteLine(SharedRoutedMoe.FormatReport(SharedRoutedMoe.RunDefault()));
Console.WriteLine(LiquidMoeOrchestrator.FormatReport(LiquidMoeOrchestrator.RunDefault()));
Console.WriteLine(EpisodicMemoryStore.FormatReport(EpisodicMemoryStore.RunDefault()));
Console.WriteLine(MiniRagPipeline.FormatReport(MiniRagPipeline.RunDefault()));
Console.WriteLine(ConceptGraph.FormatReport(ConceptGraph.RunDefault()));
Console.WriteLine(QayaCaseStudyContracts.FormatReport(QayaCaseStudyContracts.RunDefault()));
Console.WriteLine("Examples project initialized. Additional TorchSharp examples will be added in later tasks.");
